%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2

imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"

output_path: "/home/emnavi/X152b/src/autonomous_drone_sdk/global_interface/config/vins_fusion/output"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480

# swarm offset option
x_swarm_offset: 0.0
y_swarm_offset: 0.0

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1  # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 6.4154061421894948e-04, -3.3502710367888128e-02,
       9.9943842072618272e-01, 5.9400662634538415e-02,
       -9.9878077677044985e-01, -4.9355172883768450e-02,
       -1.0133427015407482e-03, 2.9243793605326522e-02,
       4.9361405768654137e-02, -9.9821923208662899e-01,
       -3.3493526433081788e-02, 5.3007796278508316e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 2.5341218693198941e-03, -3.1474746306816369e-02,
       9.9950133495222160e-01, 5.7525098658638266e-02,
       -9.9878452209491342e-01, -4.9279987120494528e-02,
       9.8045552646007527e-04, -2.0403886102343970e-02,
       4.9224553324402148e-02, -9.9828894775727406e-01,
       -3.1561370941193934e-02, 5.5599752375555506e-02, 0., 0., 0., 1. ]
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.01               # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/emnavi/X152b/src/autonomous_drone_sdk/global_interface/config/vins_fusion/output/save_files/pose_graph" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

